version: '3'
services:
  db:
    image: "mysql:8.0.12"
    command: --innodb_use_native_aio=0
    ports:
    - "3307:3306"
    env_file:
      - backend-db.env
    volumes:
    - /DockerShare/stlcbc-db:/var/lib/mysql