version: '3'
services:
  db:
    image: "mysql:8.0.12"
    command: --innodb_use_native_aio=0
    ports:
    - "3306:3306"
    env_file:
      - .env
    volumes:
    - /DockerShare/serverhealth-db:/var/lib/mysql